name: Pull Request Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: check-pr-title

  changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      dir_names: ${{ steps.changed-dirs.outputs.dir_names }}
    steps:
      - uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: checkout
          checkout_input: '{"ref": "${{ github.ref_name }}", "fetch_depth": 0}' # needs to stay until next release
          # input: |
          #   ref = "${{ github.head_ref }}"
          #   fetch_depth = 0

      - name: Detect changed directories
        id: changed-dirs
        uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: changed-dirs
          changed_dirs_input: '{"base": "main", "max_depth": 2}' # needs to stay until next release
          # input: |
          #   base = "main"
          #   max_depth = 2

  check-actions:
    needs: changed-dirs
    if: ${{ needs.changed-dirs.outputs.dir_names != '[]' }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.changed-dirs.outputs.dir_names) }}
    runs-on: ubuntu-latest
    steps:
      - uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: checkout
          checkout_input: '{"ref": "${{ github.head_ref }}", "fetch_depth": 0}' # needs to stay until next release
          # input: |
          #   ref = "${{ github.head_ref }}"
          #   fetch_depth = 0

      - name: Release (dry run)
        if: startsWith(matrix.dir, 'actions/') && matrix.dir != 'actions/yoink'
        uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: release
          release_input: '{"action_dir": "${{ matrix.dir }}", "release": true}' # needs to stay until next release
          # input: |
          #   action_dir = "${{ matrix.dir }}"
          #   release = true
