name: Test Yoink Action

on:
  push:
    branches-ignore:
      - main
    paths:
      - "images/yoink/**"
      - ".github/workflows/test-actions-yoink.yml"
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  packages: write

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: bshore/gha/actions/github@github-v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: checkout
          input: |
            ref = "${{ github.ref_name }}"
            fetch_depth = 0

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Test build
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          docker build -t ghcr.io/bshore/gha-yoink:latest \
                       -t ghcr.io/bshore/gha-yoink:sha-${SHORT_SHA} \
                       images/yoink
