name: Test Go Actions

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/test-actions-go.yml
      - actions/go/**
      - actions/yoink/**

permissions:
  contents: read

jobs:
  test-actions-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: checkout
          checkout_input: '{"ref": "${{ github.ref_name }}", "fetch_depth": 0}' # needs to stay until next release
          # input: |
          #   ref = "${{ github.ref_name }}"
          #   fetch_depth = 0

      - name: changed-dirs (versioned)
        id: changed-dirs
        uses: bshore/gha/actions/github@github-v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: changed-dirs
          input: |
            base = "main"
            max_depth = 2

      - name: Build go binary
        run: |
          mkdir -p "${RUNNER_TEMP}/actions/go/latest"
          go build -o "${RUNNER_TEMP}/actions/go/latest/go" ./actions/go

      - name: yoink
        id: yoink
        uses: ./actions/yoink

      - name: setup (source build, default glob cache key)
        uses: ./actions/go
        env:
          ACTIONS_CACHE_URL: ${{ steps.yoink.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RESULTS_URL: ${{ steps.yoink.outputs.ACTIONS_RESULTS_URL }}
          ACTIONS_RUNTIME_URL: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_URL }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: setup
          self_cache: "false"
          input: |
            go_version_file = "go.mod"

      - name: setup (source build, explicit cache key path)
        uses: ./actions/go
        env:
          ACTIONS_CACHE_URL: ${{ steps.yoink.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RESULTS_URL: ${{ steps.yoink.outputs.ACTIONS_RESULTS_URL }}
          ACTIONS_RUNTIME_URL: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_URL }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: setup
          self_cache: "false"
          input: |
            go_version_file = "go.mod"
            cache_dependency_path = "go.sum"

      - name: build (source build)
        id: build
        uses: ./actions/go
        env:
          ACTIONS_CACHE_URL: ${{ steps.yoink.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RESULTS_URL: ${{ steps.yoink.outputs.ACTIONS_RESULTS_URL }}
          ACTIONS_RUNTIME_URL: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_URL }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: build
          self_cache: "false"
          input: |
            working_directory = "./actions/github"
            output = "github-test-build"
