name: Test Go Actions

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/test-actions-go.yml
      - actions/go/**
      - actions/yoink/**

permissions:
  contents: read

jobs:
  test-actions-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: js-fatigue/gha/actions/github@github-v0.8.0
        with:
          command: checkout
          input: |
            ref = "${{ github.ref_name }}"
            fetch_depth = 0

      - name: Build go binary
        run: |
          mkdir -p "${RUNNER_TEMP}/actions/go/latest"
          go build -o "${RUNNER_TEMP}/actions/go/latest/go" ./actions/go

      - name: yoink
        id: yoink
        uses: ./actions/yoink

      - name: setup (source build, default glob cache key)
        uses: ./actions/go
        env:
          ACTIONS_CACHE_URL: ${{ steps.yoink.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RESULTS_URL: ${{ steps.yoink.outputs.ACTIONS_RESULTS_URL }}
          ACTIONS_RUNTIME_URL: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_URL }}
        with:
          command: setup
          self_cache: "false"
          input: |
            go_version_file = "go.mod"

      - name: setup (source build, explicit cache key path)
        uses: ./actions/go
        env:
          ACTIONS_CACHE_URL: ${{ steps.yoink.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RESULTS_URL: ${{ steps.yoink.outputs.ACTIONS_RESULTS_URL }}
          ACTIONS_RUNTIME_URL: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_URL }}
        with:
          command: setup
          self_cache: "false"
          input: |
            go_version_file = "go.mod"
            cache_dependency_path = "go.sum"

      - name: build (source build)
        id: build
        uses: ./actions/go
        env:
          ACTIONS_CACHE_URL: ${{ steps.yoink.outputs.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RESULTS_URL: ${{ steps.yoink.outputs.ACTIONS_RESULTS_URL }}
          ACTIONS_RUNTIME_URL: ${{ steps.yoink.outputs.ACTIONS_RUNTIME_URL }}
        with:
          command: build
          self_cache: "false"
          input: |
            {
              "working_directory": "./actions/go",
              "output": "go-test-build"
            }
